# Generated by Django 4.1.3 on 2023-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="profile_id",),
        migrations.AddField(
            model_name="userprofile",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=17, verbose_name="account_number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="bank_account"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fssai_number",
            field=models.CharField(
                blank=True, max_length=14, verbose_name="fssai_number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gst_number",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="gst_number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="incorrporation_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="incorrporation_type"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="legal_entity_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="legal_entity_name"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pan_number",
            field=models.CharField(
                blank=True, max_length=10, unique=True, verbose_name="pan_number"
            ),
        ),
    ]
