# Generated by Django 4.1.3 on 2023-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_remove_userprofile_profile_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="incorrporation_type",),
        migrations.AddField(
            model_name="userprofile",
            name="incorporation_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="incorporation_type"
            ),
        ),
    ]
