# Generated by Django 4.1.3 on 2023-03-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_remove_userprofile_incorrporation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=11, verbose_name="ifsc_code"),
        ),
    ]
